### ISSUE TITLE
changes needed before publishing v0.0.1

### ISSUE THREAD

**Issue by michaelfig** [Agoric/eventual-send#3]
@erights, would you please do a review of this package?

Let's track any required changes before the first test release here, and spin-off separate issues when they can be postponed until after the initial NPM release.

When the code is good enough for a v0.0.1 release, we'll close this issue.

**Comment by michaelfig** [comment]
Notably, I don't have any tests for `EPromise.makeRemote`.  Can you illustrate a sample usage?

**Comment by erights** [comment]
> Can you illustrate a sample usage?

Based on https://github.com/tvcutsem/es-lab/blob/master/src/ses/makeFarResourceMaker.js
See also https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch


```js
function makeFetcher(url) {
  return harden({
    GET(p, key) {
      return fetch(`${url}&q=${key}`);
    },
  };
}
```

**Comment by erights** [comment]
I am having a hard time understanding the iteration stuff starting at
https://github.com/Agoric/eventual-send/blob/master/src/index.js#L98

**Comment by michaelfig** [comment]
I was at least twice as clever as I should have been.  I've rewritten that part to use a `combinePromises` function instead, which is closer in semantics to `reduce` and thus may be easier to understand.

**Comment by michaelfig** [comment]
As @erights said in Agoric/eventual-send#7, this is good enough to release a v0.0.1.  A detailed review will come later.
