### ISSUE TITLE
Make `E` generic and move into this repository

### ISSUE THREAD

**Issue by erights** [Agoric/eventual-send#30]
Best non-syntactic way of expressing the equivalent of wavy-dot.

**Comment by warner** [comment]
I'm all for this, but is it part of the same tc39 proposal that the rest of this repo is shimming? Or is this repo for a particular implementation of an API which is merely *used* by the proposed new standard? I just wanna make sure we don't make it seem like `E()` (and maybe `E.only()`) is supposed to be part of the proposal.

**Comment by erights** [comment]
I intend to break the old "infix bang proposal" into two proposals: This one, with `makeHandled`, `E`, and `E.only` but with no syntactic changes, and a "wavy dot proposal" that is purely about adding syntactic sugar as an alternative to explicit use of `E`. I intend to propose eventual-send first.

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 30
