### ISSUE TITLE
`HandledPromise.apply` conflicts with `Function.prototype.apply`

### ISSUE THREAD

**Issue by erights** [Agoric/eventual-send#36]
See https://github.com/Agoric/SwingSet/pull/169#issuecomment-537753034

**Comment by michaelfig** [comment]
I suggest reusing `HandledPromise.applyMethod` with a property argument of `undefined`, and not having a different static method for unnamed function calls.

If that's not desirable, maybe `HandledPromise.applyFunction`?

**Comment by erights** [comment]
I think either is acceptable. Because normal usage will be using something much less verbose anyway, for this API I prefer `applyFunction`.

**Comment by erights** [comment]
FWIW, I wrote `applyFunction` into the proposal and my presentation to tc39

**Comment by michaelfig** [comment]
`applyFunction` and `applyFunctionSendOnly` are now supported on `HandledPromise`.

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 36
