### ISSUE TITLE
Chained property-gets cause infinite loop and out-of-memory

### ISSUE THREAD

**Issue by michaelfig** [Agoric/eventual-send#38]
If:

```js
x~.method1()~.y~.method2()
```

is evaluated where `x` is a remote object, and `method1` returns an object whose `y` property is a presence, the caller can loop infinitely and exhaust memory when it receives the resolution for `y`.  This can be demonstrated in the [SwingSet v0.0.26](https://github.com/Agoric/SwingSet/tree/v0.0.26) repository, but is not specific to SwingSet.

**Comment by michaelfig** [comment]
Upon investigation, a promise loop was created when forwarding unfulfilled handlers to a new handled promise.

The correction was in https://github.com/Agoric/eventual-send/commit/3450338bb2ce4038afed7f2006ebcfe7dd7ab02d#diff-1fdf421c05c1140f6d71444ea2b27638R328 to explicitly tell the postpone mechanism to use the new target promise, rather than the existing handled promise.

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 38
