### ISSUE TITLE
relay.AWAIT_FAR -> executor

### ISSUE THREAD

**Issue by michaelfig** [Agoric/eventual-send#4]
The `makeRemote` and `localRelay` components should be aware of Presences.

As discussed with @erights, the `resolve` function will no longer have special handling, and `makeRemote` will take an executor which is called with (resolve, reject, remote) callback arguments.  Then `makeRemote` will return a Promise that will only settle after one of those callbacks is invoked.  This promise is registered in the `promiseToRelay` table for the `relay` function to use.

The `remote` callback takes `(presence, resolvedRemoteRelay)`, which is registered in the `presenceToResolvedRelay` table, which is used by `localRelay`.

**Comment by michaelfig** [comment]
Needed for Agoric/agoric-sdk#123.

**Comment by michaelfig** [comment]
I would like to rename `EPromise.makeRemote` to `EPromise.makePresence` (to distinguish the new API), and call it as following:

```javascript
function executor(resolvePresence, rejectPresence) {
  // Call either:
  resolvePresence(myValue);
  // or:
  resolvePresence(myValue, myResolvedRelay);
  // or:
  rejectPresence(myReason);
}

// Give back an EPromise to a Presence.
const presence = EPromise.makePresence(executor, myUnresolvedRelay);
```

So, the original functionality of the third executor argument (`register` or `remote` as above) would be folded into the two-argument `resolvePresence(myValue, myResolvedRelay)`.  If `resolvePresence` is called with a falsey second argument, it will be the same as a plain `resolve(value)`.

Thoughts?

**Comment by erights** [comment]
why?

> // Give back an EPromise to a Presence.

When would it give back a presence?

**Comment by michaelfig** [comment]
Isn't it a promise for a presence?

If not, how would you describe the return value of makeRemote, now that we don't have makeFar?

**Comment by erights** [comment]
My mistake! I misread your sentence even as I quoted it back to you. Yes, an EPromise *to* a presence.

(I misread it for some bizarre reason as "an EPromise or a presence". I have no idea why.)

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 4
