### ISSUE TITLE
Relay method names compared to EPromise.prototype methods

### ISSUE THREAD

**Issue by michaelfig** [Agoric/eventual-send#6]
Just wondering if it makes sense to support similar relay method names as there are methods on `EPromise`?  Are the GET/PUT/DELETE/POST names a vestige of the original REST methods that should no longer be used?

**Comment by erights** [comment]
They are indeed a vestige of Tyler's bridge to REST methods. I'm inclined to keep it, as it does make a compelling introductory use of makePresence and is a correct analogy.

**Comment by michaelfig** [comment]
Okay, thanks!

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 6
